# Generated by Django 2.0.6 on 2018-06-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('route_upload_status', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_seconds', models.DecimalField(decimal_places=2, max_digits=20)),
                ('distance_meters', models.DecimalField(decimal_places=2, max_digits=20)),
                ('maximum_speed', models.DecimalField(decimal_places=14, max_digits=20)),
                ('calories', models.IntegerField()),
                ('average_heart_rate_bpm', models.IntegerField()),
                ('maximum_heart_rate_bpm', models.IntegerField()),
                ('intensity', models.CharField(max_length=30)),
                ('trigger_method', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='LapTrackPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('latitude_degrees', models.DecimalField(decimal_places=14, max_digits=16)),
                ('longitude_degrees', models.DecimalField(decimal_places=14, max_digits=17)),
                ('altitude_meters', models.DecimalField(decimal_places=14, max_digits=25)),
                ('distance_meters', models.DecimalField(decimal_places=14, max_digits=20)),
                ('heart_rate_bpm', models.IntegerField()),
                ('speed', models.DecimalField(decimal_places=14, max_digits=20)),
                ('run_cadence', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('lap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lap_track_points', to='hypoxic_service.Lap')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='lap',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_laps', to='hypoxic_service.Route'),
        ),
        migrations.AddField(
            model_name='activity',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypoxic_service.Route'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hypoxic_service.Sport'),
        ),
    ]
